### ISSUE TITLE
How to write database URL in .env file (backend)?

### ISSUE THREAD

**Issue by Alien-97** [dsc-blockchain-vote/blockchain-final-presentation#13]
Hello @ceIery @ProfDema @akshitgoyal @shubhbapna @shivangipathak01 ,

I am getting an error while deploying the backend server due to database URL bad format, i tried many formats:

```
DATABASE="myfirebaseprojectname"

DATABASE="myfirebaseprojectname.com"

DATABASE="myfirebaseprojectname.firebaseio.com"

DATABASE="https://myfirebaseprojectname.firebaseio.com"

None of those formats worked.

Error i am getting:

Can't determine Firebase Database URL.
    at FirebaseDatabaseError.FirebaseError [as constructor] (/home/user/blockchain-final-presentation/backend/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at new FirebaseDatabaseError (/home/user//blockchain-final-presentation/backend/node_modules/firebase-admin/lib/utils/error.js:205:23)

```

Thank you

**Comment by shubhbapna** [comment]
The format should be similar to the last one i.e. include the "https://"

From the docs, it says that firebase database url is constructed as "<databaseName>.firebaseio.com" or  "<databaseName>.<region>.firebasedatabase.app". Note that project name is different from database name. 

You should be able to get the database name in firebase console. After you get the the database name, set the DATABASE env value as:

DATABASE="https://<databaseName>.firebaseio.com"
