### ISSUE TITLE
WebServer not running

### ISSUE THREAD

**Issue by Alien-97** [dsc-blockchain-vote/blockchain-final-presentation#14]
Hello @shubhbapna @ceIery @akshitgoyal @shivangipathak01 @ProfDema ,

I am trying to deploy the application locally using Ganache and Truffle. I have created the project in Firebase, and the real-time database for hosting and authentication. 

Once I have configured the .env file (in my case, I called it properties.env) in both frontend and backend, imported the service-account.json, I deploy first the backend on port 5000, and then the frontend on port 3000. I get the error that can be seen in the first image, do you know what could be the cause of this error?

Is any additional configuration necessary, such as invoking functions described in API.md?

I have followed the README.md up to the point of launching the web application on the backend

My goal is to try to create-authenticate a user, and interact with the application, and then, try to do some transaction locally with Ganache and Truffle. Do you know if any additional configuration is needed that I am missing?

As you can see in the last image, my way of launching the application is to launch first the backend and then the frontend.

![error-while-deploying](https://i.ibb.co/HHDSNHF/error-al-lanzar-servidor-local.png)

I created both `.env` files in backend and frontend directories, with the following setup:

![properties-file](https://i.ibb.co/WxSVfPM/fichero-Properties-censored.jpg)

![service-account-file](https://i.ibb.co/5F9bh38/service-account.png)

![project-structure](https://i.ibb.co/nPV1P0w/backend-frontend.png)

![terminal](https://i.ibb.co/5LSyM4h/frontend-backend.png)

Thank you very much

**Comment by shubhbapna** [comment]
This is cause there is no GET / route defined in the backend.
Please refer to API.md to see which routes are defined and how to use them.

Also note that the frontend is running on port 3000 and you have used port 5000 in the browser screenshot.
